### ISSUE TITLE
🐞 - the library fails to build when TypeScript `strict` mode is enabled

### ISSUE THREAD

**Issue by jannispl** [hakimio/ngx-ui-tour#133]
### Which ngx-ui-tour-* package is the source of the bug?

md-menu

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-wau2z8-fqommk?file=package.json

### Description

After updating to v11 I am getting a build error on `ng serve`:

```
Error: node_modules/ngx-ui-tour-md-menu/lib/tour-step-template/tour-step-template.component.d.ts:10:5 - error TS2416: Property 'tourService' in type 'TourStepTemplateComponent' is not assignable to the same property in base type 'TourHotkeyListenerComponent'.
  Type 'NgxmTourService<IMdStepOption>' is not assignable to type 'TourService<IStepOption>'.
    The types of 'stepShow$.observers' are incompatible between these types.
      Type 'Observer<StepChangeParams<IMdStepOption>>[]' is not assignable to type 'Observer<StepChangeParams<IStepOption>>[]'.
        Type 'Observer<StepChangeParams<IMdStepOption>>' is not assignable to type 'Observer<StepChangeParams<IStepOption>>'.
          Type 'StepChangeParams<IStepOption>' is not assignable to type 'StepChangeParams<IMdStepOption>'.

10     tourService: NgxmTourService;
       ~~~~~~~~~~~
```

### Angular version

16

### Ngx UI Tour version

11

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
You can set [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) in your `tsconfog` while I am looking into the issue.

**Comment by hakimio** [comment]
Ok, the issue seems to only happen when `strict` mode is enabled in `tsconfig`.
I think Angular enabled `strict` mode by default in Angular 15.
Please disable `strict` mode until I figure-out what's wrong.

**Comment by hakimio** [comment]
Working StackBlitz demo: https://stackblitz.com/edit/angular-wau2z8-tdxydv?file=package.json

**Comment by hakimio** [comment]
Fixed in `v11.0.1`.
